### ISSUE TITLE
TelemetryLocationEnabler.updateTelemetryLocationState  NPE issue

### ISSUE THREAD

**Issue by lilykaiser** [mapbox/mapbox-events-android#147]
Copying from @kingfisherphuoc https://github.com/mapbox/mapbox-gl-native/issues/11929

**Platform:**
**Mapbox SDK version:**

### Steps to trigger behavior

 1. open map
 2. Using it while GPS is moving (Using Lockito or some mocklocation app)
 3. Get error as below:

```
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'com.mapbox.android.telemetry.TelemetryLocationEnabler$LocationState com.mapbox.android.telemetry.TelemetryLocationEnabler.updateTelemetryLocationState(com.mapbox.android.telemetry.TelemetryLocationEnabler$LocationState)' on a null object reference
arrow_right
com.mapbox.android.telemetry.TelemetryService.disableTelemetryLocationState (TelemetryService.java:240)
com.mapbox.android.telemetry.TelemetryService.onDestroy (TelemetryService.java:64)
android.app.ActivityThread.handleStopService (ActivityThread.java:3771)
android.app.ActivityThread.-wrap30 (ActivityThread.java)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1752)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6776)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1518)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1408)
```

### Expected behavior
We should not get this issue.
### Actual behavior
App crashed.

**Comment by Guardiola31337** [comment]
Hey @kingfisherphuoc 👋 thanks for reaching out and report your issue.

Could you add some more information for reproducing the crash (minimal example) or any other specifics around your test setup and some information on used device? What version of the Maps SDK are you using? If there is any sample or pseudo code you can provide, that would be also really helpful.

**Comment by electrostat** [comment]
I follow the logic. This looks like it'll fix the issue. I'll work on a solution.

**Comment by lilykaiser** [comment]
Fixed in https://github.com/mapbox/mapbox-events-android/pull/156
