### ISSUE TITLE
Current Location Cannot be found,shows wrong location near Nigeria.

### ISSUE THREAD

**Issue by mrunal7761** [mapbox/mapbox-events-android#158]
Current location cannot be found as per given examples in github,i tried to implement this piece of code,but not successful.
I used code example given [here.](https://www.mapbox.com/help/android-navigation-sdk/)
         
		package com.app.mapboxdemo;
		// classes needed to initialize map

		import com.mapbox.api.geocoding.v5.MapboxGeocoding;
		import com.mapbox.mapboxsdk.Mapbox;
		import com.mapbox.mapboxsdk.maps.MapView;

		// classes needed to add location layer
		import com.mapbox.geojson.Point;
		import com.mapbox.mapboxsdk.maps.MapboxMap;
		import com.mapbox.mapboxsdk.maps.OnMapReadyCallback;

		import android.location.Location;

		import com.mapbox.mapboxsdk.geometry.LatLng;

		import android.os.Bundle;
		import android.support.annotation.NonNull;

		import com.mapbox.mapboxsdk.camera.CameraUpdateFactory;
		import com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin;
		import com.mapbox.mapboxsdk.plugins.locationlayer.modes.CameraMode;
		import com.mapbox.mapboxsdk.plugins.locationlayer.modes.RenderMode;
		import com.mapbox.services.android.navigation.ui.v5.NavigationLauncherOptions;
		import com.mapbox.android.core.location.LocationEngine;
		import com.mapbox.android.core.location.LocationEngineListener;
		import com.mapbox.android.core.location.LocationEnginePriority;
		import com.mapbox.android.core.location.LocationEngineProvider;
		import com.mapbox.android.core.permissions.PermissionsListener;
		import com.mapbox.android.core.permissions.PermissionsManager;

		// classes needed to add a marker
		import com.mapbox.mapboxsdk.annotations.Marker;
		import com.mapbox.mapboxsdk.annotations.MarkerOptions;

		// classes to calculate a route
		import com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute;
		import com.mapbox.services.android.navigation.v5.navigation.NavigationRoute;
		import com.mapbox.api.directions.v5.models.DirectionsResponse;
		import com.mapbox.api.directions.v5.models.DirectionsRoute;

		import retrofit2.Call;
		import retrofit2.Callback;
		import retrofit2.Response;

		import android.support.v7.app.AppCompatActivity;
		import android.util.Log;

		// classes needed to launch navigation UI
		import android.view.View;
		import android.widget.Button;

		import com.mapbox.services.android.navigation.ui.v5.NavigationLauncher;

		// classes needed to add location layer
		import com.mapbox.geojson.Point;
		import com.mapbox.mapboxsdk.maps.MapboxMap;
		import com.mapbox.mapboxsdk.maps.OnMapReadyCallback;

		import android.location.Location;

		import com.mapbox.mapboxsdk.geometry.LatLng;

		import android.support.annotation.NonNull;

		import com.mapbox.mapboxsdk.camera.CameraUpdateFactory;
		import com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin;
		import com.mapbox.mapboxsdk.plugins.locationlayer.modes.RenderMode;
		import com.mapbox.services.android.navigation.ui.v5.NavigationLauncherOptions;
		import com.mapbox.android.core.location.LocationEngine;
		import com.mapbox.android.core.location.LocationEngineListener;
		import com.mapbox.android.core.location.LocationEnginePriority;
		import com.mapbox.android.core.location.LocationEngineProvider;
		import com.mapbox.android.core.permissions.PermissionsListener;
		import com.mapbox.android.core.permissions.PermissionsManager;

		// classes needed to add a marker
		import com.mapbox.mapboxsdk.annotations.Marker;
		import com.mapbox.mapboxsdk.annotations.MarkerOptions;

		// classes to calculate a route
		import com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute;
		import com.mapbox.services.android.navigation.v5.navigation.NavigationRoute;
		import com.mapbox.api.directions.v5.models.DirectionsResponse;
		import com.mapbox.api.directions.v5.models.DirectionsRoute;

		import retrofit2.Call;
		import retrofit2.Callback;
		import retrofit2.Response;

		import android.util.Log;

		// classes needed to launch navigation UI
		import android.view.View;
		import android.widget.Button;
		import android.widget.EditText;
		import android.widget.Toast;

		import com.mapbox.services.android.navigation.ui.v5.NavigationLauncher;

		import java.util.List;

		public class NavigationActivity extends AppCompatActivity implements LocationEngineListener, PermissionsListener {

			private MapView mapView;

			// variables for adding location layer
			private static MapboxMap map;
			private PermissionsManager permissionsManager;
			private LocationLayerPlugin locationPlugin;
			private LocationEngine locationEngine;
			private Location originLocation;

			// variables for adding a marker
			private Marker destinationMarker;
			private LatLng originCoord;
			private LatLng destinationCoord;

			// variables for calculating and drawing a route
			private Point originPosition;
			private Point destinationPosition;
			private DirectionsRoute currentRoute;
			private static final String TAG = "DirectionsActivity";
			private NavigationMapRoute navigationMapRoute;

			EditText edtLatitude, edtLongitude;

			private Button button, buttonGetLocation;

			@Override
			protected void onCreate(Bundle savedInstanceState) {
				super.onCreate(savedInstanceState);
				Mapbox.getInstance(this, getString(R.string.access_token));
				setContentView(R.layout.activity_draw_navigation);
				mapView = (MapView) findViewById(R.id.mapView);
				mapView.onCreate(savedInstanceState);

				mapView.getMapAsync(new OnMapReadyCallback() {
					@Override
					public void onMapReady(final MapboxMap mapboxMap) {

						map = mapboxMap;
						enableLocationPlugin();

						originCoord = new LatLng(originLocation.getLatitude(), originLocation.getLongitude());
						/*mapboxMap.addOnMapClickListener(new MapboxMap.OnMapClickListener() {
							@Override
							public void onMapClick(@NonNull LatLng point) {
								if (destinationMarker != null) {
									mapboxMap.removeMarker(destinationMarker);
								}
								destinationCoord = point;
								destinationMarker = mapboxMap.addMarker(new MarkerOptions()
									.position(destinationCoord)
								);

								destinationPosition = Point.fromLngLat(destinationCoord.getLongitude(), destinationCoord.getLatitude());
								originPosition = Point.fromLngLat(originCoord.getLongitude(), originCoord.getLatitude());
								getRoute(originPosition, destinationPosition);

								button.setEnabled(true);
								button.setBackgroundResource(R.color.mapboxBlue);

							}

						});*/

						button = findViewById(R.id.startButton);
						buttonGetLocation = findViewById(R.id.buttonGetLocation);
						edtLatitude = findViewById(R.id.edtLatitude);
						edtLongitude = findViewById(R.id.edtLongitude);

						buttonGetLocation.setOnClickListener(new View.OnClickListener() {
							@Override
							public void onClick(View v) {
								checkLatLong(mapboxMap);
							}
						});
						button.setOnClickListener(new View.OnClickListener() {
							public void onClick(View v) {
								Point origin = originPosition;
								Point destination = destinationPosition;

								boolean simulateRoute = true;
								NavigationLauncherOptions options = NavigationLauncherOptions.builder()
									.origin(origin)
									.destination(destination)
									.shouldSimulateRoute(simulateRoute)
									.build();
								Log.e(TAG, "onClick: Start Button" );
								// Call this method with Context from within an Activity
								NavigationLauncher.startNavigation(NavigationActivity.this, options);
							}
						});

					}
				});

			}

			private void getRoute(Point origin, Point destination) {
				NavigationRoute.builder()
					.accessToken(Mapbox.getAccessToken())
					.origin(origin)
					.destination(destination)
					.build()
					.getRoute(new Callback<DirectionsResponse>() {
						@Override
						public void onResponse(Call<DirectionsResponse> call, Response<DirectionsResponse> response) {
							// You can get the generic HTTP info about the response
							Log.d(TAG, "Response code: " + response.code());
							if (response.body() == null) {
								Log.e(TAG, "No routes found, make sure you set the right user and access token.");
								return;
							} else if (response.body().routes().size() < 1) {
								Log.e(TAG, "No routes found");
								return;
							}

							currentRoute = response.body().routes().get(0);

							// Draw the route on the map
							if (navigationMapRoute != null) {
								navigationMapRoute.removeRoute();
							} else {
								navigationMapRoute = new NavigationMapRoute(null, mapView, map, R.style.NavigationMapRoute);
							}
							navigationMapRoute.addRoute(currentRoute);
						}

						@Override
						public void onFailure(Call<DirectionsResponse> call, Throwable throwable) {
							Log.e(TAG, "Error: " + throwable.getMessage());
						}
					});
			}

			@SuppressWarnings({"MissingPermission"})
			private void enableLocationPlugin() {
				// Check if permissions are enabled and if not request
				if (PermissionsManager.areLocationPermissionsGranted(this)) {
					// Create an instance of LOST location engine

					initializeLocationEngine();

					locationPlugin = new LocationLayerPlugin(mapView, map, locationEngine);
					locationPlugin.setLocationLayerEnabled(true);
					locationPlugin.setCameraMode(CameraMode.TRACKING);
					locationPlugin.setRenderMode(RenderMode.COMPASS);
					getLifecycle().addObserver(locationPlugin);
				} else {
					permissionsManager = new PermissionsManager(this);
					permissionsManager.requestLocationPermissions(this);
				}
			}

			@SuppressWarnings({"MissingPermission"})
			private void initializeLocationEngine() {
				LocationEngineProvider locationEngineProvider = new LocationEngineProvider(this);
				locationEngine = locationEngineProvider.obtainBestLocationEngineAvailable();
				locationEngine.setPriority(LocationEnginePriority.HIGH_ACCURACY);
				locationEngine.requestLocationUpdates();
				locationEngine.activate();

				Location lastLocation = locationEngine.getLastLocation();
		//        Log.e(TAG, "initializeLocationEngine: Latitude is"+lastLocation.getLatitude()+" Longitude is "+lastLocation.getLongitude() );
				if (lastLocation != null) {
					originLocation = lastLocation;
					setCameraPosition(lastLocation);
				} else {
					locationEngine.addLocationEngineListener(this);
				}
			}

			private void setCameraPosition(Location location) {
				map.animateCamera(CameraUpdateFactory.newLatLngZoom(
					new LatLng(location.getLatitude(), location.getLongitude()), 13));
			}

			@Override
			public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
				permissionsManager.onRequestPermissionsResult(requestCode, permissions, grantResults);
			}

			@Override
			public void onExplanationNeeded(List<String> permissionsToExplain) {

			}

			@Override
			public void onPermissionResult(boolean granted) {
				if (granted) {
					enableLocationPlugin();
				} else {
					finish();
				}
			}

			@Override
			@SuppressWarnings({"MissingPermission"})
			public void onConnected() {
				locationEngine.requestLocationUpdates();
			}

			@Override
			public void onLocationChanged(Location location) {
				if (location != null) {
					originLocation = location;
					setCameraPosition(location);
					locationEngine.removeLocationEngineListener(this);
				}
			}

			@Override
			@SuppressWarnings({"MissingPermission"})
			protected void onStart() {
				super.onStart();
				if (locationEngine != null) {
					locationEngine.requestLocationUpdates();
				}
				if (locationPlugin != null) {
					locationPlugin.onStart();
				}
				mapView.onStart();
			}

			@Override
			protected void onStop() {
				super.onStop();
				if (locationEngine != null) {
					locationEngine.removeLocationUpdates();
				}
				if (locationPlugin != null) {
					locationPlugin.onStop();
				}
				mapView.onStop();
			}

			@Override
			protected void onDestroy() {
				super.onDestroy();
				mapView.onDestroy();
				if (locationEngine != null) {
					locationEngine.deactivate();
				}
			}

			@Override
			public void onLowMemory() {
				super.onLowMemory();
				mapView.onLowMemory();
			}

			@Override
			protected void onResume() {
				super.onResume();
				mapView.onResume();
			}

			@Override
			protected void onPause() {
				super.onPause();
				mapView.onPause();
			}

			@Override
			protected void onSaveInstanceState(Bundle outState) {
				super.onSaveInstanceState(outState);
				mapView.onSaveInstanceState(outState);
			}

			public void checkLatLong( MapboxMap mapboxMap)
			{
				if ((edtLatitude.getText()==null &&edtLatitude.getText().length()==0)&&(edtLongitude.getText()==null &&edtLongitude.getText().length()==0))
				{
					Toast.makeText(getApplicationContext(),"Enter Proper Longitude and Latitude.",Toast.LENGTH_LONG).show();
				}else
				{
					if (destinationMarker != null) {
						map.removeMarker(destinationMarker);
					}
					destinationCoord = new LatLng(Double.parseDouble(edtLatitude.getText().toString()), Double.parseDouble(edtLongitude.getText().toString()));
					destinationMarker = map.addMarker(new MarkerOptions()
						.position(destinationCoord)
					);

					destinationPosition = Point.fromLngLat(destinationCoord.getLongitude(), destinationCoord.getLatitude());
					originPosition = Point.fromLngLat(originCoord.getLongitude(), originCoord.getLatitude());
					getRoute(originPosition, destinationPosition);
					setCameraPosition(originLocation);
					button.setEnabled(true);
					button.setBackgroundResource(R.color.mapboxBlue);
				}
			}

		}

Permissions I used are:

       <uses-permission android:name="android.permission.INTERNET"/>
       <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
       <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
       <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
       <uses-permission android:name="android.permission.WAKE_LOCK"/>
       <uses-feature android:name="android.hardware.location.gps"/>

Gradle Details are here:

        compileSdkVersion 27

        minSdkVersion 15
        targetSdkVersion 27
        multiDexEnabled true

         implementation ('com.mapbox.mapboxsdk:mapbox-android-sdk:6.1.1@aar') {
         transitive=true
         }
         implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.5.3'
         implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.13.0'
         implementation ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.13.0') {
         transitive = true
         }

Please Help me.Thanking in Advance.

**Comment by danesfeder** [comment]
@mrunal7761 It looks like your issue here is you are never calling `LocationEngine#requestLocationUpdates` - please review https://www.mapbox.com/android-docs/core/overview/#locationengine and activate your `LocationEngine` in the same manner.

**Comment by mrunal7761** [comment]
@danesfeder ,i am using that in `onStart()`,wait let me put whole code,and you can have a look...

**Comment by mrunal7761** [comment]
@danesfeder ,now please see,and check the whole code.
Help if you can please.

**Comment by danesfeder** [comment]
@mrunal7761 can you provide a screenshot of the issue you're seeing?  Thanks!

**Comment by mrunal7761** [comment]
yes sure @danesfeder .

**Comment by mrunal7761** [comment]
[
![ss](https://user-images.githubusercontent.com/37830009/40977659-2ba64dd0-68ef-11e8-949d-4074b1fd5afe.png)
](url)

**Comment by mrunal7761** [comment]
@danesfeder as i said,it shows wrong current location as near Nigeria,somewhere in ocean.

**Comment by danesfeder** [comment]
@mrunal7761 yeah this is `null island` 🌴 (lat, lng both `0.0`) - do you eventually receive location updates?  Does this happen only initially? 

I noticed you only add the location engine listener if you have a null last location:
```
if (lastLocation != null) {
    originLocation = lastLocation;
    setCameraPosition(lastLocation);
} else {
    locationEngine.addLocationEngineListener(this);
}
``` 

Can you _always_ add this to ensure you are receiving fresh location updates from the device?

**Comment by mrunal7761** [comment]
yes in fact,if i use any fake gps application,and set any location by it,and than when i run the application,it runs exactly as required,but without setting any fake  gps location ,it always returns the same null island.

can u explain with code,so that i can understand more clearly.
@danesfeder ?

**Comment by danesfeder** [comment]
If you are using a fake GPS provider, this can "mess" with the `LocationEngine` API - like provide you a non-null update with coordinates `0.0, 0.0`.

You're also using a wifi connection and you may not be outdoors?  These can also affect the updates / accuracy of the updates. 

```
                 private void initializeLocationEngine() {
			LocationEngineProvider locationEngineProvider = new LocationEngineProvider(this);
			locationEngine = locationEngineProvider.obtainBestLocationEngineAvailable();
			locationEngine.setPriority(LocationEnginePriority.HIGH_ACCURACY);

			Location lastLocation = locationEngine.getLastLocation();
			if (lastLocation != null && lastLocation.getLongitude() != 0 && lastLocation.getLatitude() != 0) {
				originLocation = lastLocation;
				setCameraPosition(lastLocation);
			} else {
				locationEngine.addLocationEngineListener(this);
		                locationEngine.activate();
			}
		}
```

**Comment by mrunal7761** [comment]
@danesfeder ,i copied your code,and run the application by pasting it,but sorry,getting the same output.

**Comment by danesfeder** [comment]
I'd take a look at the updates you're using the set the camera position then - your GPS faker may be providing these 0 updates

**Comment by mrunal7761** [comment]
@danesfeder ,its actually an application,on which i set my current location,in that,my application shows proper output.. 
but i cant be dependent on that app,because i cant show them fake locations,i need to provide them actual current locations.
and another thing,
when in gradle file,i implement this dependencies of google play service,it shows accurat location,just by implementing them,but unfortunately i m unable to make any other transaction like getting destination for navigation,etc.
these are implementations.


           implementation 'com.google.android.gms:play-services-base:15.0.1'
           implementation 'com.google.android.gms:play-services-location:15.0.1'


Please help.

**Comment by wbearand** [comment]
@danesfeder : Unfortunately I can confirm that, it is the same for me.

I was having issues with the current location in both a MapView and NavigationView, my shown position was somewhere else and never refreshed.

when i add 
implementation 'com.google.android.gms:play-services-location:15.0.1'
i can see the location arrow on the right position. also, 
locationEngine.obtainType() changes from 
ANDROID
to
GOOGLE_PLAY_SERVICES .

But navigation does not work anymore, seems to me that locationEngine.getLastLocation() is always null.

Any ideas?

**Comment by wbearand** [comment]
It seems to me now that it works as expected.

There is just a little difference between locationEngine Type Android and GooglePlay =>
with Android, locationEngine.getLastLocation() always delivered some coordinate.

With GooglePlay, locationEngine.getLastLocation() is null, then after requestLocationUpdates sometime later onLocationChanged is triggered, and thats when location is ready, and determination of a route is possible.

**Comment by jethro-2018** [comment]
How did you resolve this? @wbearand 

I am facing the same issue, type Android never seems to retrieve a location but GooglePlay does and then navigation doesn't work as you mentioned.

**Comment by andrlee** [comment]
closing as stale and due to complete re-write of `LocationEngine`
