### ISSUE TITLE
Use IntentService with PendingIntent to receive background location updates

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-events-android#159]
Capturing from [LocationRequest documentation](https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderClient#requestLocationUpdates(com.google.android.gms.location.LocationRequest,%20android.app.PendingIntent)):

> This method is suited for the background use cases, more specifically for receiving location updates, even when the app has been killed by the system. In order to do so, use a PendingIntent for a started service. For foreground use cases, the LocationCallback version of the method is recommended, see requestLocationUpdates(LocationRequest, LocationCallback, Looper).

We currently rely on using the other method above which should be used for foreground use-cases.

**Comment by tobrun** [comment]
cc @mapbox/mobile-telemetry

**Comment by andrlee** [comment]
@tobrun now that liblocation supports both batching and background mode. can this ticket be closed? it is not super clear to me whether the scope of it also covers integration into libtelemetry? thoughts?

**Comment by andrlee** [comment]
Fixed by https://github.com/mapbox/mapbox-events-android/pull/236
