### ISSUE TITLE
Update to play-services-location:15.0.1

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-events-android#161]
We are using `11.0.4` atm, see [here](https://github.com/mapbox/mapbox-events-android/blob/master/gradle/dependencies.gradle#L12). Please update to the most recent version. With updating you will notice that FusedLocationApi has been deprecated (deprecation happened on October 24, 2017). 

cc @electrostat @zugaldia

**Comment by andrlee** [comment]
fixed by https://github.com/mapbox/mapbox-events-android/pull/229
