### ISSUE TITLE
Update MAS to 3.2.0

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-events-android#162]
Current used version of MAS is 2.2.6, see [here](https://github.com/mapbox/mapbox-events-android/blob/master/gradle/dependencies.gradle#L11). Please update to the most recent version.  Additionally do not pull in the full library if you only need a subset of the API. 

cc @electrostat @zugaldia

**Comment by electrostat** [comment]
Just checked and we actually don't require MAS in the events or core sdks. Looks to be an old dependency from the previous iteration of the library. Will remove. Thanks for catching this.
