### ISSUE TITLE
Batch location events

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-events-android#163]
To optimize background location update. It's advised to use batching of location updates.

> If your app is running in the background, the location system service computes a new location for your app only a few times each hour. This is the case even when your app is requesting more frequent location updates. By using the batched version of FLP, however, you have access to more time-frequent location history after your app receives a batch update

See related javadoc [here](https://developers.google.com/android/reference/com/google/android/gms/location/LocationRequest#setMaxWaitTime(long)).

Refs #159 

cc @electrostat @zugaldia

**Comment by andrlee** [comment]
Fixed by https://github.com/mapbox/mapbox-events-android/pull/236
