### ISSUE TITLE
Change useragent in Maps SDK for Android traffic to `mapbox-maps-android`

### ISSUE THREAD

**Issue by lilykaiser** [mapbox/mapbox-events-android#177]
Please change the useragent string for the Maps SDK for Android to `mapbox-maps-android` from `MapboxEventsAndroid`.

I did a quick spot check yesterday:
- iOS Maps SDK traffic has `mapbox-maps-ios` in the useragent
- Navigation uses `mapbox-navigation-android` or `mapbox-navigation-ios`

Changing the Android Maps SDK to `mapbox-maps-android` will bring it in line with our other mobile traffic.

Thanks!

**Comment by zugaldia** [comment]
_If_ we decide to make this change, this string should be updated too: https://github.com/mapbox/mapbox-gl-native/blob/release-espresso/platform/android/MapboxGLAndroidSDK/build.gradle#L33

**Comment by lilykaiser** [comment]
I discussed with @mick the week before last and confirmed that we would like to make this change to bring the Maps Android SDK in line with other user agents, and that making this change wouldn't break anything that exists in our back end today. I'll cut a ticket to update https://github.com/mapbox/mapbox-gl-native/blob/release-espresso/platform/android/MapboxGLAndroidSDK/build.gradle#L33

**Comment by tobrun** [comment]
PR upstream -> https://github.com/mapbox/mapbox-gl-native/pull/12706, will ship with alpha v6.5.0 today

**Comment by lilykaiser** [comment]
Thanks @tobrun ! Can https://github.com/mapbox/mapbox-events-android/pull/179 now be merged @zugaldia @electrostat ?

**Comment by electrostat** [comment]
@lilykaiser should be able to be done, as long as I get a ✅

**Comment by electrostat** [comment]
This was closed by: https://github.com/mapbox/mapbox-events-android/pull/179
