### ISSUE TITLE
Post AndroidLocationEngine#activate

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-events-android#186]
Even though we found the issue in https://github.com/mapbox/mapbox-plugins-android/issues/601, what do you think about posting the [`AndroidLocationEngine#activate`](https://github.com/mapbox/mapbox-events-android/blob/master/liblocation/src/main/java/com/mapbox/android/core/location/AndroidLocationEngine.java#L74-L76) block to the end of the message queue to not require the right order of the methods' invocation? I think this will resolve issues that users are running into as well, see https://github.com/mapbox/mapbox-plugins-android/issues/600.

**Comment by andrlee** [comment]
fixed by https://github.com/mapbox/mapbox-events-android/pull/229
