### ISSUE TITLE
Investigate NPE due to TelemetryService.obtainBoundInstances()

### ISSUE THREAD

**Issue by electrostat** [mapbox/mapbox-events-android#188]
A non-replicable bug has been reported where an NPE is thrown when attempting to obtainBoundInstances. This is caused by when stopping the Telemetry Service.

Will investigate further and track down cause/solution.

**Comment by lilykaiser** [comment]
Capturing that @zugaldia suggested internally to
> start with a null check when stopTelemetryService invokes obtainBoundInstances() as an initial workaround
