### ISSUE TITLE
3.1.5 Telemetry + 0.2.1 Core Releases

### ISSUE THREAD

**Issue by electrostat** [mapbox/mapbox-events-android#194]
### Release checklist

- [x] Change version name of Android Telemetry to `3.1.5` in `gradle.properties`
- [x] change version name of Android Core to `0.2.1` in gradle.properties 
- [x] Publish `3.1.5` and `0.2.1` artifacts to Maven Central
- [x] Change version name back to `3.2.0-SNAPSHOT` for telemetry
- [x] Change version name back to `0.3.0-SNAPSHOT` for core
- [x] Update `CHANGELOG.md`
- [x] Tag `v3.1.5 and 0.2.1` in GitHub
- [x] Make GitHub Release

Post release

- [x] Add release javadocs to appropriate spot in /android-docs `api` folder @langsmith
- [x] If new core version is being released, bump core constant version in /android-docs @langsmith
- [x] Update version #s in this repo's README @langsmith

/cc: @zugaldia @lilykaiser

**Comment by langsmith** [comment]
Done 🕺
