### ISSUE TITLE
checkApplicationContext follow-ups

### ISSUE THREAD

**Issue by lilykaiser** [mapbox/mapbox-events-android#201]
In review for https://github.com/mapbox/mapbox-events-android/pull/190, @danesfeder left the following feedback, which we should incorporate into the library.

- Is there a specific reason we don't set the applicationContext in TelemetryService#onCreate? It looks like this check has been added in a few different spots now.
- Also noting that we are using a combination of MapboxTelemetry.applicationContext and getApplication() in TelemetryService. It may make more sense to align which one is used to avoid confusion around NPEs like the one this PR resolves.

**Comment by andrlee** [comment]
Fixed with https://github.com/mapbox/mapbox-events-android/pull/265
