### ISSUE TITLE
Remove nav event creation code from the mapbox-events-android library

### ISSUE THREAD

**Issue by lilykaiser** [mapbox/mapbox-events-android#204]
Per internal conversation, step 4 in the effort to streamline tracking event ingestion is to refactor event creation code (classes, factories, test, etc...) [into the nav SDK](https://github.com/mapbox/mapbox-navigation-android/issues/1246) and out of mapbox-android-events. Creating this ticket as a placeholder.

Related maps ticket: https://github.com/mapbox/mapbox-events-android/issues/203

**Comment by Chaoba** [comment]
Related [PR](https://github.com/mapbox/mapbox-events-android/pull/383) in telemetry.

**Comment by Chaoba** [comment]
[PR](https://github.com/mapbox/mapbox-navigation-android/pull/1890) in nav sdk

**Comment by Chaoba** [comment]
@chriswu42.

**Comment by andrlee** [comment]
why are we reopening this ticket?

**Comment by Chaoba** [comment]
@andrlee we haven't done it in nav part.

**Comment by andrlee** [comment]
closing PR: https://github.com/mapbox/mapbox-events-android/pull/383 merged
