### ISSUE TITLE
MapView in recycler does not allow movement of the map

### ISSUE THREAD

**Issue by PieterVenter77** [mapbox/mapbox-events-android#206]
Hi, I have a question or potential issue regarding mapviews in a recycler. I have a recycler view with a mapbox instance as an item, however I can't really move or navigate the map, it moves a bit or just makes the recycler move. If I put mapbox in a nestedscrollview it will not display. Is there something I can set or a way of making sure a touch navigation is for the mapbox and not the recycler ? 

Would appreciate an answer in kotlin, although java is also fine :)

**Comment by tobrun** [comment]
@PieterVenter77 this issue you are noticing is that you have two views in your view hierarchy that are fighting over the touch event. You can solve this issue by an overriden onTouchIntercept event, this allows you to decide who wins this touch event. 

That said, I wouldn't advice putting a GLSurfaceView inside a scrollable container, this won't provide a great UX. For these type of designs/scenario's you should generate a map bitmap with the MapSnapshotter instead. This bitmap won't be interactive (solves use-case mentioned in OP) and will be more manageable for the RecylcerView when it comes to view caching + recreating the gl surface.

Hope this solves your issue, for future support issues please post on StackOverflow or reach out to us on https://www.mapbox.com/contact/support/. Fwiw, this repository is related to telemetry and not the maps sdk found [here](https://github.com/mapbox/mapbox-gl-native/issues).
