### ISSUE TITLE
FileAttachments seems to be sent two times

### ISSUE THREAD

**Issue by yunikkk** [mapbox/mapbox-events-android#225]
Using telemetry lib version 3.2.0 I noticed weird debugging logs about sending attachment events when `MapboxTelemetry.disable()` is called. 
Though, seems that attachments are already sent and callbacks `onAttachmentResponse` fired.

Digged a bit into a source code and looks that attachments are sent AND placed into the queue at the same time, so they later are sent one more time.

**Comment by electrostat** [comment]
Looked into this. The `AttachmentEvent` is being added to the queue still, but the files are not re-uploaded. We are basically sending the metadata of the attachments 2x. To eliminate this, we should change how we handle `sendEventIfWhitelisted`. There is a missing `return true` line within the attachment if statement, which causes the queueing logic to still continue after the fact.

**Comment by electrostat** [comment]
We also should add a unit test to check if whitelisted events are added to the queue. Will work on this tomorrow.
