### ISSUE TITLE
Trigger Release on Git-Tag Push

### ISSUE THREAD

**Issue by electrostat** [mapbox/mapbox-events-android#248]
Goal is to trigger a release when a new tag is pushed to this repo. Follow similar system in gl-native repo, suggested by @tobrun, to do a github release:
- https://github.com/mapbox/mapbox-gl-native/blob/master/circle.yml#L20
- https://github.com/mapbox/mapbox-gl-native/blob/master/circle.yml#L601
- https://github.com/mapbox/mapbox-gl-native/blob/master/circle.yml#L637

cc: @andrlee

**Comment by andrlee** [comment]
fixed with https://github.com/mapbox/mapbox-events-android/pull/385
