### ISSUE TITLE
Start/Stop Service vs Bind/Unbind

### ISSUE THREAD

**Issue by electrostat** [mapbox/mapbox-events-android#250]
`startService`/`stopService` and `bindService`/`unbindService` are used within logic of controlling our telemetry service. We need to weed out duplicate code and make sure there are no logic holes that would result into the system not functioning properly. (i.e. `unbindService` won't stop service started with `startService`).

**Comment by andrlee** [comment]
no longer an issue due to: https://github.com/mapbox/mapbox-events-android/pull/351
