### ISSUE TITLE
Release libcore with #217 more specific Proguard rules

### ISSUE THREAD

**Issue by linnar** [mapbox/mapbox-events-android#258]
I would like to use the more specific rules introduced in #217 but the currently released version 0.2.1 of libcore does not include this improvement and 0.3.0-SNAPSHOT is not compatible with other libraries used in 6.6.1 release of mapbox-android-sdk. Thank you for considering this or explaining current release roadmap.

**Comment by andrlee** [comment]
@linnar we plan to release major update of maps sdk, which includes major updates of libcore and libtelemetry in December. Hope this timeline works for you.

**Comment by linnar** [comment]
Thank you, I wasn't sure it about this as I already saw the pull request in the release notes. I will plan with this timeline in mind.
