### ISSUE TITLE
4.0.0 Telemetry + 1.0.0 Core Release

### ISSUE THREAD

**Issue by electrostat** [mapbox/mapbox-events-android#259]
### Release checklist

- [x] Change version name of Android Telemetry to `4.0.0` in `gradle.properties`
- [x] change version name of Android Core to `1.0.0` in gradle.properties 
- [x] Publish `4.0.0` and `1.0.0` artifacts to Maven Central
- [x] Change version name back to `4.1.0-SNAPSHOT` for telemetry
- [x] Change version name back to `1.1.0-SNAPSHOT` for core
- [x] Update `CHANGELOG.md`
- [x] Tag `v4.0.0 and 1.0.0` in GitHub
- [x] Make GitHub Release

Post release

- [x] Add release javadocs to appropriate spot in /android-docs `api` folder @langsmith
- [x]  If new core version is being released, bump core constant version in /android-docs @langsmith

/cc: @andrlee @benlevin47

**Comment by andrlee** [comment]
@electrostat one thing we might need to fix before releasing is `@since 3.0.0` -> `@since 1.0.0` annotations in liblocation public api.

**Comment by langsmith** [comment]
Done on my end @electrostat 🎊
