### ISSUE TITLE
Move telemetry classes into different packages

### ISSUE THREAD

**Issue by Chaoba** [mapbox/mapbox-events-android#271]
@andrlee Currently, all telemetry class are in the same package, so the source codes are unclear and hard to read. It will be better if we create more packages and move corresponding classes into right packages.

**Comment by andrlee** [comment]
@Chaoba telemetry refactor is on the way. I'm working on libcore refactor and other location related changes, we have another ticket that captures all refactor requirements for libtelemetry.

**Comment by Chaoba** [comment]
Got it, closed.
