### ISSUE TITLE
Unable to disable telemetry on Android

### ISSUE THREAD

**Issue by andrlee** [mapbox/mapbox-events-android#281]
Link to original ticket: https://github.com/mapbox/mapbox-gl-native/issues/13304

**Comment by andrlee** [comment]
@Chaoba these two tickets might be related: https://github.com/mapbox/mapbox-gl-native/issues/14235.

**Comment by Chaoba** [comment]
@andrlee IMHO they are different scenario.

**Comment by andrlee** [comment]
closing, since the telemetry toggle has been re-written as part of: https://github.com/mapbox/mapbox-events-android/pull/351. Please re-open if issue persists.
