### ISSUE TITLE
NullPointerException in TelemetryUtils.obtainApplicationState() 

### ISSUE THREAD

**Issue by chancyWu** [mapbox/mapbox-events-android#298]
Platform: android 8
Mapbox SDK version: 6.7.0

Even though i disable the telemetry,
```     
        TelemetryDefinition telemetry = Mapbox.getTelemetry();
        telemetry.setUserTelemetryRequestState(false);
```
 the error still happen and cause the app crash. The crash log is as below: quite similar to #170 
> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
>        at com.mapbox.android.telemetry.TelemetryUtils.obtainApplicationState(TelemetryUtils.java:103)
>        at com.mapbox.android.telemetry.LocationEvent.<init>(LocationEvent.java:44)
>        at com.mapbox.android.telemetry.LocationMapper.createLocationEvent(LocationMapper.java:32)
>        at com.mapbox.android.telemetry.LocationMapper.from(LocationMapper.java:18)
>        at com.mapbox.android.telemetry.LocationReceiver.sendEvent(LocationReceiver.java:47)
>        at com.mapbox.android.telemetry.LocationReceiver.onReceive(LocationReceiver.java:26)
>        at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
>        at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
>        at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
>        at android.os.Handler.dispatchMessage(Handler.java:108)
>        at android.os.Looper.loop(Looper.java:166)
>        at android.app.ActivityThread.main(ActivityThread.java:7425)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by andrlee** [comment]
closing as stale
