### ISSUE TITLE
GoogleLocationEngineImpl intermittently provides delayed updates

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-events-android#348]
In the past week or so of field testing, we have been experiencing some weird behavior from [`GoogleLocationEngineImpl`](https://github.com/mapbox/mapbox-events-android/blob/master/liblocation/src/main/java/com/mapbox/android/core/location/GoogleLocationEngineImpl.java)

The engine, at startup (first request for updates), takes 30 seconds - 1 min to begin a steady stream of updates.  Once the updates begin though, the behavior is fine (steady updates for the rest of the session).  In navigation, this creates a "lag" or "freeze" at the beginning of navigation as the user is trying to orient themselves.

This behavior is intermittent, but has been reported by multiple clients in the past (see https://github.com/mapbox/mapbox-navigation-android/issues/1764, https://github.com/mapbox/mapbox-navigation-android/issues/1469#issuecomment-442450591) - both resolved by providing the wrapper snippet.

We have been providing our own snippets that seem to be helping (https://github.com/mapbox/mapbox-navigation-android/issues/1764#issuecomment-467152558).  I haven't had time to dig into what the difference is between these snippets and the location lib implementation.

**Comment by andrlee** [comment]
Based on my preliminary analysis, this is specific to Pie and it looks like it is more sensitive to location request parameters. We've been defaulting to displacement of 3.0m to save on battery but it seems the internal implementation details have evolved around this, so i will remove all default value settings from our wrapper internally.

**Comment by andrlee** [comment]
fixed with https://github.com/mapbox/mapbox-events-android/pull/350
