### ISSUE TITLE
Release Core 1.2.0

### ISSUE THREAD

**Issue by electrostat** [mapbox/mapbox-events-android#353]
### Release checklist

- [x] Change version name of Android Telemetry to `4.2.0` in `gradle.properties`
- [x] change version name of Android Core to `1.2.0` in gradle.properties 
- [x] toggle off telemetry release
- [x] Publish `1.2.0` artifact to Maven Central
- [x] Change version name back to `4.3.0-SNAPSHOT` for telemetry
- [x] Change version name back to `1.3.0-SNAPSHOT` for core
- [x]  toggle telemetry release back on
- [x] Update `CHANGELOG.md`
- [x] Tag `v1.2.0` in GitHub
- [x] Make GitHub Release

Post release

- [x] Add release javadocs to appropriate spot in /android-docs `api` folder @langsmith

/cc: @andrlee

**Comment by langsmith** [comment]
Done on my end @electrostat  🚀
