### ISSUE TITLE
Remove arch.core + support dependencies

### ISSUE THREAD

**Issue by electrostat** [mapbox/mapbox-events-android#359]
During testing the current `4.3.0-SNAPSHOT` within the maps sdk, I discovered that we are importing duplicate and conflicting dependencies that is causing issues for the main maps sdk. Excluding them within the gradle removes this problem.

Error Log: `Error: Program type already present: android.support.v4.content.LocalBroadcastManager$BroadcastRecord`

Excluding both `localbroadcastmanager` and `support-compat` fixes the issue within the maps sdk.

Solution is to downgrade to using `27.1.1` version of the support library. We currently are on `28.0.0` and then changing to using `support-core-utils` which contains both `localbroadcastmanager` and `support-compat` in the older library version.

**Comment by andrlee** [comment]
@electrostat can you put detailed description what have conflicted (error logs) and what you have excluded exactly to make it work? also snapshot of maps and ours `dependencies.gradle` won't hurt to have attached as well..
