### ISSUE TITLE
com.android.support:support-core-utils usage

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-events-android#376]
```
     +--- com.mapbox.mapboxsdk:mapbox-android-telemetry:4.3.0
     |    +--- com.squareup.okhttp3:okhttp:3.10.0 -> 3.12.0
     |    |    \--- com.squareup.okio:okio:1.15.0
     |    +--- com.google.code.gson:gson:2.8.2 -> 2.8.5
     |    +--- com.android.support:support-annotations:27.1.1
     |    +--- com.mapbox.mapboxsdk:mapbox-android-core:1.2.0
     |    \--- com.android.support:support-core-utils:27.1.1
     |         +--- com.android.support:support-annotations:27.1.1
     |         \--- com.android.support:support-compat:27.1.1
     |              +--- com.android.support:support-annotations:27.1.1
     |              \--- android.arch.lifecycle:runtime:1.1.0
     |                   +--- android.arch.lifecycle:common:1.1.0
     |                   \--- android.arch.core:common:1.1.0
```

Was wondering what the scope of `com.android.support:support-core-utils` is and if it could be potentially removed/downsized?

**Comment by andrlee** [comment]
@tobrun this change was introduced by: https://github.com/mapbox/mapbox-events-android/pull/363
best fix imho is to bump all support libraries to `28.x.x` then only `localbroadcastmanager` and `support-compat` will be added (perhaps i can even get rid of `support-compat`). what's your thoughts about it?

**Comment by tobrun** [comment]
thanks for following up, was just wondering ;) at some point, when some enterprise customers allow, we should migrate to androidx. 

> **perhaps i can even get rid of support-compat). **

the more we drop the better but we are also using support-compat in maps so wouldn't make a difference for us.
