### ISSUE TITLE
4.4.0 Telemetry Release

### ISSUE THREAD

**Issue by andrlee** [mapbox/mapbox-events-android#386]
### Release checklist

- [x]  Update snapshot version `4.5.0-SNAPSHOT` for telemetry
- [x]  Update `CHANGELOG.md`
- [x]  Tag `4.4.0` in GitHub
- [x]  Make GitHub Release
- [x]  Publish `4.4.0` artifact to Maven Central

Post release

- [x] Add release javadocs to appropriate spot in /android-docs `api` folder @langsmith

/cc: @mapbox/mobile-telemetry

**Comment by langsmith** [comment]
Done here 🎬

**Comment by andrlee** [comment]
thanks @langsmith !
