### ISSUE TITLE
1.3.0 Core Release 

### ISSUE THREAD

**Issue by andrlee** [mapbox/mapbox-events-android#391]
### Release checklist

- [x]  Update snapshot version `1.4.0-SNAPSHOT`
- [x]  Update `CHANGELOG.md`
- [x]  Tag `1.3.0` in GitHub
- [x]  Make GitHub Release
- [x]  Publish `1.3.0` artifact to Maven Central

Post release

- [x] Add release javadocs to appropriate spot in /android-docs `api` folder @langsmith

/cc: @mapbox/mobile-telemetry

**Comment by langsmith** [comment]
🎉 🎉 🏁🚗
