### ISSUE TITLE
'onPermissionResult' not called after granting location permission in Fragment

### ISSUE THREAD

**Issue by asegestam** [mapbox/mapbox-events-android#395]
Hello, im using a Fragment to show the Mapbox map. I've followed the steps in the guides but they dont seem to work properly inside a fragment. I get the notification popup, and when I grant permission the method 'onPermissionResult'  is never called so I can't react to the user granting permission so my app just waits. It does work however when I restart the app, then it recognizes that the permission is granted.

Im calling for permission `PermissionsManager.areLocationPermissionsGranted(context)` returns false and by calling `permissionsManager.requestLocationPermissions(requireActivity())` .
And I've implemented the `PermissionsListener` and overidden these methods: `onPermissionResult,` `onExplanationNeeded` and `onRequestPermissionsResult`

**Comment by andrlee** [comment]
hey @asegestam thanks for reporting this, could you please post your code snippet with `PermissionsManager` in use?

**Comment by asegestam** [comment]
Ok, so I have a Fragment implementing `PermissionsListener`. First I enable the location component in `onViewCreated` with this method where I check if the permission is granted, and if not I ask for it:  
``` 
private fun enableLocationComponent(loadedMapStyle: Style) {
        // Check if permissions are enabled and if not request
        if (PermissionsManager.areLocationPermissionsGranted(context)) {
            // Activate the MapboxMap LocationComponent to show user location
            val locationComponentOptions = LocationComponentOptions.builder(requireContext())
                    .trackingGesturesManagement(false)
                    .build()
            mapboxMap?.let {
                it.locationComponent.apply {
                    activateLocationComponent(LocationComponentActivationOptions.builder(requireContext(), loadedMapStyle)
                            .locationComponentOptions(locationComponentOptions)
                            .useDefaultLocationEngine(true)
                            .build())
                    isLocationComponentEnabled = true
                    // Set the component's camera mode
                    cameraMode = CameraMode.NONE
                    initCamera()
                }
            }
        } else {
            permissionsManager.requestLocationPermissions(requireActivity())
        }
    }
```
and then I have the overriden methods from `PermissionsListener`
```
    override fun onRequestPermissionsResult(requestCode: Int, permissions: Array<String>, grantResults: IntArray) {
        permissionsManager.onRequestPermissionsResult(requestCode, permissions, grantResults)
    }

    override fun onExplanationNeeded(permissionsToExplain: List<String>) {
        Toast.makeText(requireContext(), R.string.user_location_permission_explanation, Toast.LENGTH_LONG).show()
    }

    override fun onPermissionResult(granted: Boolean) {
        if (granted) {
            Log.d("onPermissionResult", "permission granted")
            enableLocationComponent(getMapStyle()!!)
        } else {
            Toast.makeText(requireContext(), R.string.user_location_permission_not_granted, Toast.LENGTH_LONG).show()
            permissionsManager.requestLocationPermissions(requireActivity())
        }
    }
```
The log in `onPermissionResult` is never made, even if I grant the permission.

**Comment by andrlee** [comment]
@Chaoba can you please take a look when you have a chance?

**Comment by Chaoba** [comment]
@andrlee No problem, I will take a look at it.

**Comment by Chaoba** [comment]
@asegestam Thanks for your report.

In `PermissionManager` we will request permission with `ActivityCompat` in this [line](https://github.com/mapbox/mapbox-events-android/blob/5b5ca7e04cb8fab31a8dc040b6e7521f930a58a4/liblocation/src/main/java/com/mapbox/android/core/permissions/PermissionsManager.java#L84), so `onRequestPermissionsResult` callback is called on the activity and not the fragment.

You can change your codes to send the request in `Activity` instead of `Fragment` in order to get the callback.

Hopefully this could resolve your question.

**Comment by asegestam** [comment]
> @asegestam Thanks for your report.
> 
> In `PermissionManager` we will request permission with `ActivityCompat` in this [line](https://github.com/mapbox/mapbox-events-android/blob/5b5ca7e04cb8fab31a8dc040b6e7521f930a58a4/liblocation/src/main/java/com/mapbox/android/core/permissions/PermissionsManager.java#L84), so `onRequestPermissionsResult` callback is called on the activity and not the fragment.
> 
> You can change your codes to send the request in `Activity` instead of `Fragment` in order to get the callback.
> 
> Hopefully this could resolve your question.

Thank you, this resolved the issue.

**Comment by ankitgupta394** [comment]
I requested location permission from a fragment and in the fragment, I needed to change this:

 ActivityCompat.requestPermissions(getActivity(), new String[]{
                Manifest.permission.ACCESS_FINE_LOCATION, Manifest.permission.ACCESS_COARSE_LOCATION}, LOCATION_REQ_CODE)

to this:

 requestPermissions(new String[]{
                Manifest.permission.ACCESS_FINE_LOCATION, Manifest.permission.ACCESS_COARSE_LOCATION}, LOCATION_REQ_CODE);

Then onRequestPermissionsResult will be called in fragment also
