### ISSUE TITLE
Mapbox crashes with InterruptedException

### ISSUE THREAD

**Issue by TankJK** [mapbox/mapbox-events-android#399]
App is getting continuous crash with InterruptedException.

FATAL EXCEPTION: OkHttp events.mapbox.com Writer
java.lang.InterruptedException
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:1991)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2025)
at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1048)
at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:776)
at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:820)

Device is Android Samsung S5 with Android 5.0

### Steps to reproduce

 1.App was trying to place the marker and showing route
 2.App crashes randomly after some time.
 3.

### Expected behavior
App should not crash

### Actual behavior
App crashes

### Configuration

**Android versions:** 
Android 5.0
**Device models:** 
Samsung S5 
**Mapbox SDK versions:** 
com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.37.0

**Comment by Guardiola31337** [comment]
> do you mind taking a look at this? Seems to be from events.mapbox.com Writer?

Transferred to `mapbox-events-android`

cc @andrlee

**Comment by andrlee** [comment]
@TankJK it does look like internal crash in okhttp3 library and it's unrelated to mapbox. we don't use `ScheduledThreadPoolExecutor` in events library. Can you try to switch to the earlier stable version of `okhttp` and retest?

**Comment by andrlee** [comment]
> Seems to be from events.mapbox.com Writer?

@danesfeder this is an `okhttp` internal log, not from `events` as far as i can tell.

**Comment by TankJK** [comment]
@andrlee I have tried with okhttp3 with version 3.10.0 but its still crashing.

**Comment by andrlee** [comment]
Can you share your code here?

**Comment by TankJK** [comment]
@andrlee Which part of code you are interested?

**Comment by andrlee** [comment]
@TankJK the part that is likely triggering crash event. You mentioned you do place the marker and showing route. I'd be interested to know if removing "showing route" logic from the app fixes the problem.

**Comment by TankJK** [comment]
@andrlee sometimes application is crashing when just only marker is shown.

**Comment by Chaoba** [comment]
@TankJK Can you create a simple test project on Github that could reproduce this issue? So we can download and test it.

**Comment by andrlee** [comment]
hey @TankJK any updates? thanks!

**Comment by TankJK** [comment]
@andrlee From last couple of days, surprisingly application is not getting this crash. I am still using same version of okhttp3 and mapbox navigation ui.

**Comment by andrlee** [comment]
closing as per customer's feedback.
