### ISSUE TITLE
🐞 ANR caused by GzipRequestInterceptor

### ISSUE THREAD

**Issue by andrlee** [mapbox/mapbox-events-android#403]
**Configuration**
 - SDK Version: 4.4.1
 - Android OS Version: 8.0.0
 - Device model(s): MFDX-EXPLORER
 - App: Customer's app in production

**Steps to Reproduce**
ANR reported from device in production.

**Expected**
Telemetry library does not produce ANRs

**Logging**
`com.mapbox.android.telemetry.GzipRequestInterceptor.intercept(GzipRequestInterceptor.java:36)`
Thread info: `tid:143|name:|ANR-WatchDog|priority:5`

**Comment by Chaoba** [comment]
I am confused here. Our sending request is sent in background thread, how could this cause ANR?

**Comment by andrlee** [comment]
closing as false positive
