### ISSUE TITLE
🔨 API to change baseUrl for every Environment at runtime

### ISSUE THREAD

**Issue by korshaknn** [mapbox/mapbox-events-android#418]
**Feature**
API to change `baseUrl` for every `Environment` at runtime

**Customers**
vision team

**Impact**
vision team need possibility to change `urls` at runtime depending on current country

**Comment by alfwatt** [comment]
cc: @andrlee

**Comment by korshaknn** [comment]
implemented in [PR 420](https://github.com/mapbox/mapbox-events-android/pull/420)
