### ISSUE TITLE
Add test app example of listening to device network connectivity changes

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-events-android#427]
I'm trying to figure out how to listen to device connectivity changes. Could be good to have a minimal example in this repo's test app that shows how to do this. What I'm envisioning is some sort of TextView change, Snackbar, Toast, etc. that declares a change in connectivity. E.g. a toast says `disconnected` when the device was connected to the internet and _then_ put into airplane mode.

**Comment by alfwatt** [comment]
Clarified that this is for network changes, we have something similar in iOS provided by the reachability API. e.g.: https://beebom.com/how-get-iphone-reachability-andriod/

**Comment by langsmith** [comment]
Thanks @alfwatt . 

Related is the (lack of docs) at https://docs.mapbox.com/android/core/overview/#connectivitylistener. I'm happy to advise/do the building out of more docs, when a test app example is present.  👍

**Comment by andrlee** [comment]
@langsmith https://docs.mapbox.com/android/core/overview/#connectivitylistener should be deprecated. Framework does provide mechanism to monitor network state: https://developer.android.com/reference/android/net/ConnectivityManager. Mind closing it?

**Comment by langsmith** [comment]
Ok, closing as I misunderstood that `/mapbox-events-android` would provide some sort of callback about network change. Apparently this doesn't working reliably across multiple OS versions and the behavior is inconsistent. Because it does not, it's out of the scope of this repo's test app. 

The following method is used in several Mapbox SDKs/apps. It seems that it could be used with a background service running every XX seconds/minutes to check and report connectivity:

```
private boolean deviceHasInternetConnection() {
	ConnectivityManager connectivityManager = (ConnectivityManager)
	getApplicationContext().getApplicationContext().getSystemService(Context.CONNECTIVITY_SERVICE);
	    if (connectivityManager != null) {
	      NetworkInfo activeNetwork = connectivityManager.getActiveNetworkInfo();
	      return activeNetwork != null && activeNetwork.isConnected();
	    }
	    return false;
}
```

Regarding @andrlee's suggestion for docs deprecation, I've ticketed it at https://github.com/mapbox/mapbox-events-android/issues/428 for tracking. 

Thanks everyone!
