### ISSUE TITLE
🚀 Release Core/1.4.0 Telemetry/4.7.0

### ISSUE THREAD

**Issue by harvsu** [mapbox/mapbox-events-android#439]
**Timeline**
Week of Nov 18th

**Pre-release Testing**
- [x] Manual downstream test app test with snapshot
- [x] Manual offline test with telemetry test app
- [x] Check for memory leaks
- [x] Run manual battery tests

**Release Checklist**
- [x] Update snapshot version `4.7.0-SNAPSHOT`/`1.4.0-SNAPSHOT`
- [x] Update `CHANGELOG.md`
- [x] Tag `4.7.0`/ `1.4.0` in GitHub
- [x] Make GitHub Release
- [x] Publish `4.7.0`/ `1.4.0` artifact to Maven Central

**Post Release**
- [x] Add release javadocs to appropriate spot in /android-docs `api` folder @langsmith

/cc: @mapbox/mobile-telemetry

**Comment by langsmith** [comment]
Done here 🎆 🎉
