### ISSUE TITLE
Upgrade to AndroidX

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-events-android#446]
We are still relying on support libraries:
https://github.com/mapbox/mapbox-events-android/blob/master/gradle/dependencies.gradle

To completely remove support libraries from maps sdk, we need to update this to AndroidX equivalents.

**Comment by zugaldia** [comment]
@tobrun will we be using this updated Telem SDK with AndroidX on Hydrogen, Carbon, or both?

**Comment by tobrun** [comment]
both, this is a requirement for a enterprise customer switching from building from source to consuming our published binaries. In normal cases, a user could leverage jetifier to replace the support libraries coming from this library but this specific customer isn't using gradle and thus unable to use jetifier.

**Comment by nkukday** [comment]
#450
