### ISSUE TITLE
🚀 Telemetry Release 4.7.2

### ISSUE THREAD

**Issue by harvsu** [mapbox/mapbox-events-android#454]
**Timeline**
Week of Feb 17th

**Pre-release Testing**
- [x] Manual downstream test app test with snapshot
- [x] Manual offline test with telemetry test app
- [x] Check for memory leaks
- [x] Run manual battery tests

**Release Checklist**
- [x] Update snapshot version `4.7.3-SNAPSHOT`
- [x] Update `CHANGELOG.md`
- [x] Tag `4.7.2` in GitHub
- [x] Make GitHub Release
- [x] Publish `4.7.2` artifact to Maven Central

**Post Release**
- [x] Add release javadocs to appropriate spot in /android-docs `api` folder @langsmith

/cc: @mapbox/mobile-telemetry

**Comment by harvsu** [comment]
Thanks!! @langsmith

**Comment by langsmith** [comment]
I just merged https://github.com/mapbox/android-docs/pull/1227. Done here! 

![giphy-12](https://user-images.githubusercontent.com/4394910/75064045-093edc00-549b-11ea-9c2a-b8475640433f.gif)
