### ISSUE TITLE
🚀 Telemetry Release 4.7.3

### ISSUE THREAD

**Issue by harvsu** [mapbox/mapbox-events-android#459]
**Timeline**
Week of Feb 24th

**Pre-release Testing**
- [x] Manual downstream test app test with snapshot
- [x] Manual offline test with telemetry test app
- [x] Check for memory leaks
- [x] Run manual battery tests

**Release Checklist**
- [x] Update snapshot version `4.7.4-SNAPSHOT`
- [x] Update `CHANGELOG.md`
- [x] Tag `4.7.3` in GitHub
- [x] Make GitHub Release
- [x] Publish `4.7.3` artifact to Maven Central

**Post Release**
- [x] Add release javadocs to appropriate spot in /android-docs `api` folder @langsmith

/cc: @mapbox/mobile-telemetry

**Comment by langsmith** [comment]
Done here!
