### ISSUE TITLE
🚀 [Core/Telemetry] Release Telem 5.0.0/Core 2.0.0

### ISSUE THREAD

**Issue by harvsu** [mapbox/mapbox-events-android#471]
**Timeline**
Week of March 23rd

**Pre-release Testing**
- [x] Manual downstream test app test with snapshot
- [x] Manual offline test with telemetry test app
- [x] Check for memory leaks
- [x] Run manual battery tests

**Release Checklist**
- [x] Update snapshot version `5.0.1-SNAPSHOT/2.0.1-SNAPSHOT`
- [x] Update `CHANGELOG.md`
- [x] Tag `Telem 5.0.0/Core 2.0.0` in GitHub
- [x] Make GitHub Release
- [x] Publish `5.0.0/2.0.0` artifact to Maven Central

**Post Release**
- [x] Add release javadocs to appropriate spot in /android-docs `api` folder @langsmith

/cc: @mapbox/mobile-telemetry @mapbox/maps-sdk-leads
/cc: @mapbox/navigation-android  @mapbox/vision-android @mapbox/maps-android

**Comment by langsmith** [comment]
Done!

![giphy](https://user-images.githubusercontent.com/4394910/77570267-b8027d80-6e88-11ea-9353-4e486d48c941.gif)
