### ISSUE TITLE
Add a request for ACCESS_BACKGROUND_LOCATION  to PermissionsManager

### ISSUE THREAD

**Issue by evabishchevich** [mapbox/mapbox-events-android#490]
**Feature**
Android 10 introduced [a `background location` access](https://developer.android.com/training/location/permissions#background). It would be nice to support this feature in the SDK.

**Comment by Guardiola31337** [comment]
https://github.com/mapbox/mapbox-events-android/blob/9ffd11611c85c5cda1f42c2506a01080b79a4b8c/liblocation/src/main/java/com/mapbox/android/core/permissions/PermissionsManager.java#L59-L85 is not asking for `ACCESS_BACKGROUND_LOCATION`

**Comment by nagineni** [comment]
Fixed in https://github.com/mapbox/mapbox-events-android/pull/498
