### ISSUE TITLE
Add equals support for LocationEngineRequets

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-events-android#506]
It'd be great if `LocationEngineRequest` overrode `equals`/`hashCode`, especially to improve the unit testing experience.

**Comment by kmadsen** [comment]
We will want to do this before moving it to the NavigationOptions https://github.com/mapbox/mapbox-navigation-android/pull/3804

**Comment by LukasPaczos** [comment]
@mapbox/core-sdk would there be a chance for a patch release including the above changes, just as a precaution? I wouldn't necessarily expect anyone to compare the `NavigationOptions` classes in the production code, but we cannot truly rule it out.

/cc @zugaldia @Guardiola31337
