### ISSUE TITLE
❔ Can recent releases be pushed to Maven Central?

### ISSUE THREAD

**Issue by lognaturel** [mapbox/mapbox-events-android#563]
Thanks to all who have worked on these libraries. I'm involved in [ODK](https://getodk.org/) and we produce open source tools for mobile data collection. Our [Android mobile client](https://github.com/getodk/collect) uses Mapbox maps for capturing locations.

My understanding is that this repo is now deprecated because Mapbox has shifted to a monorepo at https://github.com/mapbox/mapbox-maps-android, did I get that correctly?

It looks like this repo still is under the MIT license and has had several releases since the ones [available on Maven Central](https://mvnrepository.com/artifact/com.mapbox.mapboxsdk). Could a maintainer please push [those releases](https://github.com/mapbox/mapbox-events-android/releases) to Central? Specifically, we'd like to upgrade `telemetry` because of some crashes that were fixed in `7.0.x` point releases (`7.0.0` is the last available).

**Comment by tarigo** [comment]
Hi @lognaturel,

https://github.com/mapbox/mapbox-maps-android is a repo for the [actual version v10](https://docs.mapbox.com/android/maps/guides/) of Maps SDK,  https://github.com/mapbox/mapbox-gl-native-android is for the old [legacy, yet maintained, version v9](https://docs.mapbox.com/android/legacy/maps/guides/).

Mapbox provides SDKs via Maven (https://api.mapbox.com/downloads/v2/releases/maven), here is the guide to help you: https://docs.mapbox.com/android/legacy/maps/guides/install/#add-the-dependency. All the latest releases are there.

**Comment by lognaturel** [comment]
Thanks for the quick response, @tarigo! I didnt realize 9.x would still be maintained but use the Mapbox distribution. Would you consider publishing the telemetry 7.x point releases to Maven Central as well?

We’re an open source project for which mapping is a small component. It doesn’t make sense for everyone wanting to build the source to have to manage Mapbox credentials. We’re not sure what we’re going to do long term but for now we’ve been advised by the community team to stay on 9.2.1. That’s ok but we’re seeing excessive crashes caused by some of the telemetry bugs.

Thanks for your help!

**Comment by lognaturel** [comment]
Thanks! We’ll keep the dependencies local for now. 

> implies that the end users of ODK SDK have to manage their credentials

Absolutely. But not including those credentials means a small part of the app fails at run time. That’s pretty different from the app not building. 

I appreciate all the alternate suggestions. I understand these don’t seem like a big deal but they involve overhead that’s significant to us. As it sounds like you’ve found working with sonatype does for you.
