### ISSUE TITLE
Hello Im also currently experiencing this telemetry bug using the unity mapbox package. is there a way to fix this for unity as well? my app has been crashing alot with this being the last error

### ISSUE THREAD

**Issue by bomturbo** [mapbox/mapbox-events-android#586]
Hello Im also currently experiencing this telemetry bug using the unity mapbox package. is there a way to fix this for unity as well? my app has been crashing alot with this being the last error

`Error initializing telemetry: UnityEngine.AndroidJavaException: java.lang.IllegalArgumentException: com.opticalethegame.opticaleTest: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.`

_Originally posted by @smart09091 in https://github.com/mapbox/mapbox-events-android/issues/578#issuecomment-1793756237_

**Comment by tatiana-yan** [comment]
Hello! We have a similar issue here: https://github.com/mapbox/mapbox-events-android/issues/585.
Let's use that one to track the problem. I close this issue as a duplicate.

**Comment by bomturbo** [comment]
https://drive.google.com/file/d/17DLghBiTA3_g-NrSULPBlGglBcdGAOwI/view?usp=drivesdk
