### ISSUE TITLE
Optional location provider results in logging warnings

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-events-android#68]
due to making location provider optional, we are receiving warnings as:

> I/art: Rejecting re-init on previously-failed class java.lang.Class<com.mapbox.mapboxsdk.location.LocationSource>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapzen/android/lost/api/LostApiClient$ConnectionCallbacks;

Could we look into suppressing these warnings or finding a way that they don't occur?

refs https://github.com/mapbox/mapbox-gl-native/issues/11285

cc @Guardiola31337

**Comment by Guardiola31337** [comment]
After removing Lost dependencies completely (👀 https://github.com/mapbox/mapbox-events-android/pull/81 which landed recently) these warnings shouldn't occur anymore.

@tobrun could you confirm if the warnings are gone now?

**Comment by Guardiola31337** [comment]
Now that https://github.com/mapbox/mapbox-gl-native/releases/tag/android-v6.0.0-beta.5 and https://github.com/mapbox/mapbox-events-android/releases/tag/telem-3.0.0-beta.3-core-0.2.0-beta.3 are released and available 🎉 @tobrun could you please retest this and report back if it's still an issue?

**Comment by andrlee** [comment]
closing as stale, @tobrun please re-open if it's still an issue
