### ISSUE TITLE
Add test coverage for AlarmReceiver

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-events-android#74]
- We should add some `AlarmReceiver` missing tests

👀 https://github.com/mapbox/mapbox-events-android/pull/73#discussion_r171848700

**Comment by alfwatt** [comment]
@Guardiola31337 - reviling this, do we still need to make this change or can we close the issue?

**Comment by Guardiola31337** [comment]
Currently there are a couple of `AlarmReceiver` related tests 👀 https://github.com/mapbox/mapbox-events-android/blob/master/libtelemetry/src/androidTestFull/java/com/mapbox/android/telemetry/AlarmReceiverInstrumentationTest.java https://github.com/mapbox/mapbox-events-android/blob/master/libtelemetry/src/testFull/java/com/mapbox/android/telemetry/AlarmReceiverTest.java so I believe you can go ahead and close it. @andrlee could you confirm that we're good here?

**Comment by alfwatt** [comment]
Closing: https://github.com/mapbox/mobile-telemetry/issues/458
