### ISSUE TITLE
Remove LOST from available LocationEngine types

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-events-android#76]
Since https://github.com/mapbox/mapbox-events-android/pull/58, passing `LOST` when requesting new `LocationEngine` just results in `null`. Can we remove that type from `LocationEngine#Type`?

/cc @electrostat

**Comment by electrostat** [comment]
Being addressed by: https://github.com/mapbox/mapbox-events-android/pull/81

**Comment by Guardiola31337** [comment]
https://github.com/mapbox/mapbox-events-android/pull/81 landed.

Closing.

cc @electrostat
