### ISSUE TITLE
Bring back the Mock location engine type

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-events-android#82]
- `MOCK` `LocationEngine.Type` was removed in #81 👀 https://github.com/mapbox/mapbox-events-android/pull/81/files#diff-f30d9c26536d598f49a2e375aa2aec9fL21 and shouldn't because it's used in the Nav SDK 👉 https://github.com/mapbox/mapbox-navigation-android/blob/cf93796b03575ee83e2fbe6370ef261d66ba8759/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/location/MockLocationEngine.java#L188

cc @electrostat @zugaldia @danesfeder @devotaaabel

**Comment by zugaldia** [comment]
How important is this for the Nav SDK from nice-to-have to release-blocker?

**Comment by Guardiola31337** [comment]
Having a `MOCK` `LocationEngine.Type` makes sense to me because 3rd party clients will be able to create their own "mock" location engines.

BTW it's a one line fix :sweat_smile:, I'll submit a PR 🚀

**Comment by Guardiola31337** [comment]
> BTW it's a one line fix 😅, I'll submit a PR 🚀

There you go #83
