### ISSUE TITLE
Change naming in libcore/libtelemetry javadoc.gradle ?

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-events-android#88]
https://github.com/mapbox/mapbox-events-android/blob/5f8c4986d9d190875383c4f1ce23dcc6e5c7ea90/libcore/javadoc.gradle

https://github.com/mapbox/mapbox-events-android/blob/5f8c4986d9d190875383c4f1ce23dcc6e5c7ea90/libtelemetry/javadoc.gradle

The `javadoc.gradle` files in this repo ( 👆) still have mention of `Mapbox Android Services`.  

@electrostat , @cammace , @zugaldia , any thoughts on whether this should be changed to a title like `Mapbox Android Core` or something ? Kept as is?

**Comment by langsmith** [comment]
I ask because I'm cleaning up javadocs related to this repo and it is a bit strange to see MAS as the major header of libcore/libtelemetry javadocs....


<img width="940" alt="screen shot 2018-03-19 at 3 07 58 pm" src="https://user-images.githubusercontent.com/4394910/37624967-58af6140-2b87-11e8-901b-9c6118e43fa1.png">

**Comment by electrostat** [comment]
Yeah that looks like a legacy issue from when Telemetry was a part of MAS. I would recommend changing it to `Mapbox Android Telemetry`, since core gets packaged up and set along with telemetry.

**Comment by langsmith** [comment]
Got it
